matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - set -o pipefail
        - xcodebuild test -scheme PromiseK-macOS -configuration Debug | xcpretty -c
        - xcodebuild test -scheme PromiseK-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme PromiseK-tvOS -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme PromiseK-watchOS -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
    - os: osx
      language: generic
      osx_image: xcode10
      script:
        - swift --version
        - swift build
        - swift test
    - os: linux
      language: generic
      sudo: required
      env: SWIFT_VERSION=4.2
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test
